version: "3.9"
services:

  backend-service:
    build:
      context: "../Backend/"
      dockerfile: "dockerfile"
    hostname: Backend
    container_name: Backend
    ports:
      - "8081:8081"
    depends_on:
      - db

  frontend-gateway:
    build:
      context: "../hello-world/"
      dockerfile: "Dockerfile"
    hostname: frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend-service

  db:
    image: "mysql:latest"
    environment:
        MYSQL_DATABASE: 'mysql'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'user'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'password'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
    expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
    volumes:
        - my-db:/var/lib/mysql
volumes:
  my-db: